/* global document, window */
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const { chromium } = require('playwright');
(async () => {
 const executablePath = process.env.CLEX_BROWSER_EXECUTABLE || process.argv[2];
 const browser = await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});
 const page = await browser.newPage({viewport:{width:1440,height:1000}});
 const runtimeErrors=[]; page.on('pageerror',error=>runtimeErrors.push(error.message));
 const data=()=>page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('clex-flow:projects:v1'))).map(value=>JSON.parse(value))[0]);
 const pin = id=>page.getByRole('button',{name:new RegExp(`^Контакт ${id}:`)});
 const terminal = name=>page.getByRole('button',{name,exact:true});
 const saved=()=>page.getByRole('button',{name:'Сохранить',exact:true}).first().isDisabled();
 try {
 await fs.mkdir('.artifacts',{recursive:true});
 await page.goto(process.env.CLEX_PREVIEW_URL || 'http://127.0.0.1:1420');
 await page.getByRole('button',{name:'Новый проект',exact:true}).first().click();
 await page.getByRole('textbox',{name:'Название проекта'}).fill('Mount Test');
 await page.getByRole('button',{name:'Создать проект',exact:true}).click();
 await page.getByRole('heading',{name:'Mount Test',exact:true}).waitFor();
 await page.getByRole('button',{name:'Монтаж',exact:true}).click();
 await page.getByText('Ревизия не подтверждена',{exact:true}).first().waitFor();
 await page.getByRole('button',{name:'Добавить: Внешний светодиод',exact:true}).click();
 await terminal('Внешний светодиод 1: Анод через R').click();
 await pin('P36').click();
 await page.getByRole('alert').filter({hasText:'а не к питанию'}).waitFor();
 await pin('P34').click();
 await page.getByRole('combobox',{name:'Подключение: Катод / GND'}).selectOption('P28');
 await page.getByRole('button',{name:'Добавить: Кнопка',exact:true}).click();
 assert.equal(await page.getByRole('combobox',{name:'Подключение: Сигнал / GPIO'}).locator('option[value="P34"]').evaluate(option=>option.disabled),true);
 await terminal('Кнопка 1: Сигнал / GPIO').click();
 await pin('P34').click();
 await page.getByRole('alert').filter({hasText:'уже назначен'}).waitFor();
 await pin('P32').click();
 await page.getByRole('alert').filter({hasText:'разделяется с камерой'}).waitFor();
 await page.getByRole('button',{name:'Отменить соединение',exact:true}).click();
 await page.locator('.board-drawing').click();
 await page.getByRole('combobox',{name:'Камера на разъёме',exact:true}).selectOption('disconnected');
 await page.getByRole('button',{name:'Компонент Кнопка 1',exact:true}).click();
 await page.getByRole('combobox',{name:'Подключение: Сигнал / GPIO'}).selectOption('P32');
 await page.getByRole('combobox',{name:'Подключение: Общий / GND'}).selectOption('P28');
 await page.locator('.assembly-validation').getByText('Ошибок монтажа нет',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Сохранить',exact:true}).first().click();
 await page.getByText('Проект сохранён',{exact:true}).waitFor();
 const initial=await data(); assert.equal(initial.formatVersion,3); assert.equal(initial.components.length,2); assert.equal(initial.assembly.connections.length,4); assert.deepEqual(initial.gpioAssignments.map(item=>item.gpio).sort((a,b)=>a-b),[16,17]);
 await page.getByRole('button',{name:'Увеличить монтаж',exact:true}).click();
 assert.equal(await saved(),false);
 await page.getByRole('button',{name:'Показать весь монтаж',exact:true}).click();
 await page.screenshot({path:'.artifacts/clex-flow-assembly.png'});
 const node=page.getByRole('button',{name:'Компонент Кнопка 1',exact:true});
 const box=await node.boundingBox();
 await page.mouse.move(box.x+60,box.y+20); await page.mouse.down(); await page.mouse.move(box.x+100,box.y+55,{steps:6}); await page.mouse.up();
 await page.getByRole('button',{name:'Сохранить',exact:true}).first().click();
 await page.getByText('Проект сохранён',{exact:true}).waitFor();
 const moved=await data(); assert.notDeepEqual(moved.assembly.positions[moved.components[1].id],initial.assembly.positions[initial.components[1].id]);
 await page.reload(); await page.locator('.project-open').click(); await page.getByRole('button',{name:'Монтаж',exact:true}).click();
 assert.equal(await page.locator('.physical-wire').count(),4);
 await page.getByRole('button',{name:'Компонент Кнопка 1',exact:true}).click();
 assert.equal(await page.getByRole('combobox',{name:'Подключение: Сигнал / GPIO'}).inputValue(),'P32');
 await page.locator('.board-drawing').click();
 await page.getByRole('combobox',{name:'Камера на разъёме',exact:true}).selectOption('connected');
 await page.locator('.assembly-validation').getByText('Ошибок: 1',{exact:true}).waitFor();
 await page.getByRole('combobox',{name:'Камера на разъёме',exact:true}).selectOption('disconnected');
 await page.getByRole('button',{name:'Компонент Внешний светодиод 1',exact:true}).click();
 await page.getByRole('spinbutton',{name:'Резистор, Ом',exact:true}).fill('100');
 await page.locator('.validation-row').filter({hasText:'расчётный ток'}).waitFor();
 await page.getByRole('spinbutton',{name:'Резистор, Ом',exact:true}).fill('330');
 await page.getByRole('button',{name:'Удалить компонент',exact:true}).click();
 assert.equal(await page.locator('.physical-wire').count(),2);
 await page.getByRole('button',{name:/^ESP32-S3-DevKitC-1/}).click();
 await page.getByRole('dialog',{name:'Сменить плату?',exact:true}).waitFor();
 await page.getByRole('button',{name:'Отмена',exact:true}).click();
 assert.equal(await page.locator('.physical-wire').count(),2);
 await page.getByRole('button',{name:/^ESP32-S3-DevKitC-1/}).click();
 await page.getByRole('button',{name:'Сменить плату',exact:true}).click();
 assert.equal(await page.locator('.physical-wire').count(),0);
 assert.equal(await page.locator('.hardware-node').count(),1);
 await page.getByRole('textbox',{name:'Поиск компонентов',exact:true}).fill('светодиод');
 assert.equal(await page.getByRole('button',{name:'Добавить: Кнопка',exact:true}).count(),0);
 await page.getByRole('textbox',{name:'Поиск компонентов',exact:true}).fill('');
 await page.setViewportSize({width:1000,height:700});
 const boardBox=await page.locator('.board-drawing').boundingBox(), canvasBox=await page.locator('.assembly-svg').boundingBox();
 assert.ok(boardBox.x>=canvasBox.x-1 && boardBox.y>=canvasBox.y-1 && boardBox.x+boardBox.width<=canvasBox.x+canvasBox.width+1 && boardBox.y+boardBox.height<=canvasBox.y+canvasBox.height+1,'Board fits after changing model and resizing');
 await page.screenshot({path:'.artifacts/clex-flow-assembly-small.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
 assert.deepEqual(runtimeErrors,[]);
 console.log('PASS: LED + button wiring, power/GPIO conflict/camera rejection, camera settings, validation, format3 save/reload, viewport, drag, resistor checks, removal cleanup, board-change confirmation, search, 1000x700. No runtime errors.');
 } catch (error) { await page.screenshot({path:'.artifacts/clex-flow-assembly-failure.png'}); console.error(await page.locator('.physical-wire').evaluateAll(elements => elements.map(element => element.getAttribute('aria-label')))); throw error; } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
