/* global getComputedStyle, document, window */
const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
 const {displayModule}=await import('./display-fixture.js');
 const {eth}=await import('./catalog-fixture.js');
 let fixture;
 const browser=await chromium.launch({headless:true,executablePath:process.env.CLEX_BROWSER_EXECUTABLE||process.argv[2]});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 const saved=()=>page.evaluate(()=>JSON.parse(Object.values(JSON.parse(localStorage.getItem('clex-flow:projects:v1')))[0]));
 const save=async()=>{await page.getByRole('button',{name:'Сохранить',exact:true}).first().click();await page.getByText('Проект сохранён',{exact:true}).waitFor();};
 try{
  await page.goto(process.env.CLEX_PREVIEW_URL||'http://127.0.0.1:1420');
  await page.getByRole('button',{name:'Новый проект',exact:true}).first().click();
  await page.getByRole('textbox',{name:'Название проекта'}).fill('Display test');
  await page.getByRole('button',{name:'Создать проект',exact:true}).click();
  await page.getByRole('button',{name:'Монтаж',exact:true}).click();await page.locator('.assembly-flow-region[data-ready="true"]').waitFor();
  await page.getByRole('combobox',{name:'Камера на разъёме',exact:true}).selectOption('disconnected');
  await page.getByRole('button',{name:'Добавить: '+displayModule.name,exact:true}).click();
  const pins={gnd:'P28',vcc:eth.pins.find(p=>p.kind==='power'&&p.voltage===3.3).id};
  for(const [terminal,gpio] of [['sclk',16],['mosi',17],['cs',18],['dc',15],['reset',38]])pins[terminal]=eth.pins.find(p=>p.gpio===gpio).id;
  for(const terminal of displayModule.terminals)await page.getByRole('combobox',{name:'Подключение: '+terminal.label,exact:true}).selectOption(pins[terminal.id]);
  await save();fixture=await saved();
  assert.equal(await page.getByRole('combobox',{name:'Подключение: VCC · 3,3 В'}).inputValue(),fixture.assembly.connections.find(w=>w.terminalId==='vcc').boardPinId);
  assert.equal(displayModule.terminals.some(t=>t.id==='bl'),false);
  await page.getByRole('button',{name:'Логика',exact:true}).click();
  await page.getByRole('button',{name:'Добавить блок: Экран дисплея',exact:true}).click();
  await page.locator('.logic-node').first().dblclick();
  const dialog=page.getByRole('dialog');await dialog.waitFor();
  await dialog.getByRole('button',{name:'Добавить текст',exact:true}).click();
  await dialog.getByRole('combobox',{name:'Шрифт и размер',exact:true}).selectOption('montserrat_14');
  await dialog.getByLabel('Фон экрана',{exact:true}).fill('#123456');
  await dialog.getByLabel('Цвет текста',{exact:true}).fill('#ffdd00');
  await dialog.getByLabel('Координата X',{exact:true}).fill('30');
  await dialog.getByLabel('Координата Y',{exact:true}).fill('50');
  const text=dialog.locator('[data-screen-element]');const box=await text.boundingBox();
  await page.mouse.move(box.x+10,box.y+10);await page.mouse.down();await page.mouse.move(box.x+45,box.y+45,{steps:8});await page.mouse.up();
  assert.ok(Number(await dialog.getByLabel('Координата X',{exact:true}).inputValue())>30,'text moves by dragging');
  const paddings=await dialog.locator('select').evaluateAll(elements=>elements.map(e=>({top:parseFloat(getComputedStyle(e).paddingTop),bottom:parseFloat(getComputedStyle(e).paddingBottom)})));
  assert.ok(paddings.every(p=>p.top>=8&&p.bottom>=8));
  await page.screenshot({path:'.artifacts/display-editor.png'});
  await dialog.getByRole('button',{name:'Сохранить интерфейс',exact:true}).click();
  await page.locator('.logic-display-preview').getByText('Привет, мир! CLEX Flow',{exact:true}).waitFor();
  await save();const current=await saved(),id=fixture.components[0].id;
  await require('node:fs/promises').writeFile('.artifacts/display-ui-project.json',JSON.stringify(current));
  assert.equal(current.logic.nodes[0].parameters.componentId,id);assert.equal(current.screens[id].background,'#123456');assert.equal(current.screens[id].elements[0].fontId,'montserrat_14');
  assert.deepEqual(current.gpioAssignments,fixture.gpioAssignments);assert.deepEqual(current.assembly.connections,fixture.assembly.connections);
  await page.getByRole('button',{name:'Посмотреть исходники прошивки',exact:true}).click();
  await page.getByRole('button',{name:'main/main.c',exact:true}).click();
  assert.match(await page.locator('.firmware-source').innerText(),/lv_label_set_text/);await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Открыть редактор экрана',exact:true}).click();
  await dialog.getByRole('button',{name:'Добавить текст',exact:true}).click();await dialog.getByRole('button',{name:'Отмена',exact:true}).click();
  await page.reload();await page.locator('.project-open').click();await page.getByRole('button',{name:'Логика',exact:true}).click();
  await page.locator('.logic-node').dblclick();await dialog.waitFor();assert.equal(await dialog.locator('[data-screen-element]').count(),1);
  await page.setViewportSize({width:1000,height:700});await page.screenshot({path:'.artifacts/display-editor-small.png'});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
  await page.keyboard.press('Escape');assert.deepEqual(errors,[]);
  console.log('PASS: shared hardware instance, display block, double-click editor, font/background/color, text drag, padded selects, preview, firmware generation, cancel and reload, 1000x700.');
 }catch(error){await page.screenshot({path:'.artifacts/display-ui-failure.png'});throw error;}finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
