/* global document, window */
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const { chromium } = require('playwright');
(async () => {
 const executablePath = process.env.CLEX_BROWSER_EXECUTABLE || process.argv[2];
 const browser = await chromium.launch({ headless:true, ...(executablePath ? { executablePath } : {}) });
 const page = await browser.newPage({viewport:{width:1440,height:940}});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 try {
 await fs.mkdir('.artifacts', { recursive: true });
 await page.goto(process.env.CLEX_PREVIEW_URL || 'http://127.0.0.1:1420');
 await page.getByText('Здесь начнётся ваша коллекция').waitFor();
 await page.screenshot({path:'.artifacts/clex-flow-home.png'});
 await page.getByRole('button',{name:'Новый проект',exact:true}).first().click();
 await page.getByRole('textbox',{name:'Название проекта'}).fill('Blink Test');
 await page.getByRole('button',{name:'Создать проект',exact:true}).click();
 await page.getByRole('heading',{name:'Blink Test',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Собрать',exact:true}).isDisabled(),true);
 await page.getByRole('textbox',{name:'Описание',exact:true}).fill('Внешний светодиод: проверка сохранения');
 await page.getByRole('button',{name:'Сохранить',exact:true}).first().click();
 await page.getByText('Проект сохранён',{exact:true}).waitFor();
 await page.screenshot({path:'.artifacts/clex-flow-workspace.png'});
 await page.reload();
 await page.getByRole('heading',{name:'Blink Test',exact:true}).waitFor();
 await page.locator('.project-open').click();
 assert.equal(await page.getByRole('textbox',{name:'Описание',exact:true}).inputValue(),'Внешний светодиод: проверка сохранения');
 await page.getByRole('textbox',{name:'Описание',exact:true}).fill('Несохранённое изменение');
 await page.getByRole('button',{name:'Мои проекты',exact:false}).click();
 await page.getByRole('dialog').waitFor();
 await page.getByRole('button',{name:'Отмена',exact:true}).click();
 assert.equal(await page.getByRole('textbox',{name:'Описание',exact:true}).inputValue(),'Несохранённое изменение');
 await page.getByRole('button',{name:'Мои проекты',exact:false}).click();
 await page.getByRole('button',{name:'Не сохранять',exact:true}).click();
 await page.locator('.project-open').click();
 assert.equal(await page.getByRole('textbox',{name:'Описание',exact:true}).inputValue(),'Внешний светодиод: проверка сохранения');
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'Экспорт JSON',exact:true}).click();
 const download=await downloadPromise; await download.saveAs('.artifacts/clex-flow-export.json');
 const original=JSON.parse(await fs.readFile('.artifacts/clex-flow-export.json','utf8'));
 assert.equal(original.name,'Blink Test');
 await page.getByRole('button',{name:'Мои проекты',exact:false}).click();
 await page.getByRole('button',{name:'Переименовать Blink Test',exact:true}).click();
 await page.getByRole('textbox',{name:'Название проекта'}).fill('Blink Renamed');
 await page.getByRole('button',{name:'Сохранить название',exact:true}).click();
 await page.getByRole('heading',{name:'Blink Renamed',exact:true}).waitFor();
 await page.getByRole('textbox',{name:'Поиск проектов'}).fill('absent');
 await page.getByText('Проекты не найдены').waitFor();
 await page.getByRole('textbox',{name:'Поиск проектов'}).fill('Blink');
 await page.getByRole('heading',{name:'Blink Renamed',exact:true}).waitFor();
 const chooserPromise=page.waitForEvent('filechooser');
 await page.getByRole('button',{name:'Открыть JSON',exact:true}).click();
 await (await chooserPromise).setFiles('.artifacts/clex-flow-export.json');
 await page.getByRole('heading',{name:'Blink Test',exact:true}).waitFor();
 await page.getByRole('button',{name:'Мои проекты',exact:false}).click();
 assert.equal(await page.locator('.project-card').count(),2);
 await page.getByRole('button',{name:'Удалить Blink Renamed',exact:true}).click();
 await page.getByRole('button',{name:'Оставить проект',exact:true}).click();
 assert.equal(await page.locator('.project-card').count(),2);
 await page.getByRole('button',{name:'Удалить Blink Renamed',exact:true}).click();
 await page.getByRole('button',{name:'Удалить проект',exact:true}).click();
 assert.equal(await page.locator('.project-card').count(),1);
 await page.reload();
 await page.getByRole('heading',{name:'Blink Test',exact:true}).waitFor();
 assert.equal(await page.locator('.project-card').count(),1);
 await fs.writeFile('.artifacts/clex-flow-invalid.json','{"formatVersion":999}');
 const invalidChooser=page.waitForEvent('filechooser');
 await page.getByRole('button',{name:'Открыть JSON',exact:true}).click();
 await (await invalidChooser).setFiles('.artifacts/clex-flow-invalid.json');
 await page.getByRole('alert').waitFor();
 assert.equal(await page.locator('.project-card').count(),1);
 await page.setViewportSize({width:1000,height:700});
 await page.getByRole('button',{name:'Скрыть ошибку',exact:true}).click();
 await page.screenshot({path:'.artifacts/clex-flow-small.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth > window.innerWidth),false);
 assert.deepEqual(errors,[]);
 console.log('PASS: create, save, reload, unsaved cancel/discard, export/import copy, rename, search, delete confirmation/persistence, invalid format, 1000x700 layout. No browser runtime errors.');
 } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1});
