import { Layers, Cpu, Trash2, Copy, ArrowRight, Info, TriangleAlert } from 'lucide-react';
import { graphModule, hardwareBinding, TYPE_NAMES, TYPE_COLORS } from './model.js';

export default function LogicInspector({ project, catalog, selection, busy, onChange, onRemove, onDuplicate, issues }) {
  const node = selection.nodes.length === 1 ? project.logic.nodes.find(node => node.id === selection.nodes[0]) : null;
  const edge = !node && selection.edges.length === 1 ? project.logic.edges.find(edge => edge.id === selection.edges[0]) : null;
  if (node) {
    const module = graphModule(node, catalog), binding = hardwareBinding(node, project, catalog);
    const problems = issues.filter(issue => issue.nodeId === node.id);
    return <><div className="panel-label">СВОЙСТВА БЛОКА</div><label className="field">Название блока<input value={node.name} maxLength={80} disabled={busy} onChange={event => onChange(node.id, { name: event.target.value }, `name:${node.id}`)} /></label><span className="badge purple">v{node.moduleVersion} · {module?.categoryName || 'Модуль не установлен'}</span><p className="panel-note">{module?.description || `Требуется ${node.moduleId} версии ${node.moduleVersion}.`}</p><div className="property-divider" />
      {module?.version === node.moduleVersion && Object.entries(module.parameters).map(([key, parameter]) => <label className="field" key={key}>{parameter.label}{parameter.type === 'component' ? <select disabled={busy} value={node.parameters[key]} onChange={event => onChange(node.id, { parameters: { ...node.parameters, [key]: event.target.value } })}><option value="">Выберите компонент</option>{node.parameters[key] && !project.components.some(component => component.id === node.parameters[key]) && <option value={node.parameters[key]}>Компонент удалён</option>}{project.components.filter(component => module.constraints.hardware.modules.includes(component.moduleId)).map(component => <option key={component.id} value={component.id}>{component.name}</option>)}</select> : parameter.type === 'boolean' ? <select value={String(node.parameters[key])} disabled={busy} onChange={event => onChange(node.id, { parameters: { ...node.parameters, [key]: event.target.value === 'true' } })}><option value="true">Высокий / true</option><option value="false">Низкий / false</option></select> : parameter.type === 'text' ? <textarea rows={4} maxLength={parameter.maxLength} disabled={busy} value={node.parameters[key]} onChange={event => onChange(node.id, { parameters: { ...node.parameters, [key]: event.target.value } }, `param:${node.id}:${key}`)} /> : <input type="number" min={parameter.min} max={parameter.max} step={parameter.step} value={node.parameters[key]} disabled={busy} onChange={event => onChange(node.id, { parameters: { ...node.parameters, [key]: Number(event.target.value) } }, `param:${node.id}:${key}`)} />}</label>)}
      {module?.constraints.hardware && <div className="logic-hardware-binding"><Cpu size={17} /><div><strong>{binding.component?.name || 'Компонент не выбран'}</strong><span>{binding.gpio === null ? 'GPIO не назначен' : `GPIO${binding.gpio} · ${module.constraints.hardware.mode === 'output' ? 'выход' : 'вход'}`}</span></div></div>}
      {problems.length > 0 && <div className="logic-problems">{problems.map((issue, index) => <p key={index} className={issue.severity === 'error' ? 'problem-error' : ''}><TriangleAlert size={13} />{issue.message}</p>)}</div>}
      <div className="panel-label connections-heading">ПОРТЫ БЛОКА</div>{[['inputs', 'Входы'], ['outputs', 'Выходы']].map(([key, title]) => module?.[key].length > 0 && <div className="inspector-ports" key={key}><strong>{title}</strong>{module[key].map(port => <span key={port.id}><i style={{ background: TYPE_COLORS[port.type] }} />{port.name}<small>{TYPE_NAMES[port.type]}</small></span>)}</div>)}<p className="panel-note">Нажмите подпись выхода, затем входа, или перетащите соединение за круглый порт.</p><div className="inspector-node-actions"><button className="button secondary" disabled={busy} onClick={onDuplicate}><Copy size={14} />Дублировать блок</button><button className="button remove-component" disabled={busy} onClick={onRemove}><Trash2 size={14} />Удалить блок</button></div></>;
  }
  if (edge) {
    const source = project.logic.nodes.find(node => node.id === edge.source), target = project.logic.nodes.find(node => node.id === edge.target);
    return <><div className="panel-label">СВЯЗЬ ЛОГИКИ</div><span className="badge" style={{ color: TYPE_COLORS[edge.dataType] }}>{TYPE_NAMES[edge.dataType]}</span><div className="logic-edge-detail"><strong>{source?.name}</strong><small>{edge.sourceHandle}</small><ArrowRight size={18} /><strong>{target?.name}</strong><small>{edge.targetHandle}</small></div><p className="panel-note">Типы портов должны совпадать. Событие запускает действие; данные передают значение.</p><button className="button remove-component" disabled={busy} onClick={onRemove}><Trash2 size={15} />Удалить связь</button></>;
  }
  return <><div className="panel-label">ВИЗУАЛЬНАЯ ЛОГИКА</div><div className="logic-inspector-intro"><Layers size={35} /><h3>{selection.nodes.length > 1 ? `Выделено блоков: ${selection.nodes.length}` : 'От события к действию'}</h3><p>Таймер → Переключение GPIO</p></div><p className="panel-note">Таймер задаёт ритм. Действие использует компонент, уже подключённый во вкладке «Монтаж».</p><div className="property-divider" /><div className="property-pair"><span>Блоков</span><code>{project.logic.nodes.length}</code></div><div className="property-pair"><span>Связей</span><code>{project.logic.edges.length}</code></div><p className="panel-note"><Info size={15} />Граф сохраняется автоматически после паузы в редактировании. Монтаж и свойства без изменений графа сохраняются вручную.</p>{selection.nodes.length > 1 && <div className="inspector-node-actions"><button className="button secondary" disabled={busy} onClick={onDuplicate}><Copy size={15} />Дублировать выделение</button><button className="button remove-component" disabled={busy} onClick={onRemove}><Trash2 size={15} />Удалить выделение</button></div>}<div className="logic-shortcuts"><span>⌘/Ctrl Z <b>Отменить</b></span><span>⌘/Ctrl Shift Z <b>Повторить</b></span><span>⌘/Ctrl C / V <b>Копировать / вставить</b></span><span>⌘/Ctrl D <b>Дублировать</b></span></div><p className="fine-print">Редактор не выполняет граф и не считывает устройство. Сборка и Serial доступны через верхнюю панель десктопного приложения.</p></>;
}
