import { useState } from 'react';
import { Search, Plus, Timer, ScanLine, ArrowUpRight, Repeat2, Terminal, Box, Layers } from 'lucide-react';
import { TYPE_COLORS, TYPE_NAMES } from './model.js';
const icons = { Timer, ScanLine, ArrowUpRight, Repeat2, Terminal };
export default function LogicLibrary({ modules, busy, onAdd }) {
  const [search, setSearch] = useState(''), [category, setCategory] = useState('all');
  const categories = [...new Map(modules.map(module => [module.category, module.categoryName])).entries()];
  const visible = modules.filter(module => (category === 'all' || module.category === category) && `${module.name} ${module.description}`.toLocaleLowerCase('ru').includes(search.toLocaleLowerCase('ru')));
  return <><div className="panel-label">ЛОГИЧЕСКИЕ БЛОКИ</div><label className="search component-search"><Search size={14} /><input aria-label="Поиск блоков" value={search} onChange={event => setSearch(event.target.value)} placeholder="Найти блок…" /></label><div className="category-filter"><button className={category === 'all' ? 'active' : ''} onClick={() => setCategory('all')}>Все</button>{categories.map(([id, name]) => <button key={id} className={category === id ? 'active' : ''} onClick={() => setCategory(id)}>{name}</button>)}</div><div className="logic-library">{visible.map(module => { const Icon = icons[module.icon] || Box; return <button key={module.id} className="hardware-library-item" onClick={() => onAdd(module)} disabled={busy} aria-label={`Добавить блок: ${module.name}`}><span style={{ color: module.color }}><Icon size={20} /></span><div><strong>{module.name}</strong><small>{module.categoryName}</small></div><Plus size={14} /></button>; })}{!visible.length && <p className="panel-note">Блоки не найдены.</p>}</div><div className="panel-label library-title">ТИПЫ СОЕДИНЕНИЙ</div><div className="logic-type-legend">{Object.entries(TYPE_NAMES).map(([type, name]) => <span key={type}><i style={{ background: TYPE_COLORS[type] }} />{name}</span>)}</div><p className="panel-note">Событие запускает действие. Значение передаёт данные. Несовместимые типы и циклы запрещены.</p><div className="library-bottom"><Layers size={14} />5 проверяемых типов блоков · локально</div></>;
}
