import { Cpu, Info, Trash2, Unplug, TriangleAlert, CheckCircle2, ArrowRight } from 'lucide-react';
import { terminalSide, TERMINAL_SIDES } from './terminalLayout.js';
import { moduleFor, moduleProblem, connectionProblem, pinProblem } from './model.js';

function Sources({ board }) {
  return <details className="board-sources"><summary>Официальные источники</summary>{board.sources.map(source => <div key={source.url}><strong>{source.title}</strong><code>{source.url}</code></div>)}</details>;
}

export default function AssemblyInspector({ project, board, catalog, selection, busy, onConnect, onDisconnect, onRemoveWire, onRemoveComponent, onComponentChange, onBoardSetting, onTerminalSide }) {
  const component = selection?.type === 'component' && project.components.find(item => item.id === selection.id);
  const module = component && moduleFor(component, catalog);
  const wire = selection?.type === 'wire' && project.assembly.connections.find(item => item.id === selection.id);
  const pin = selection?.type === 'pin' && board.pins.find(item => item.id === selection.id);
  if (component) {
    const incompatible = moduleProblem(component, catalog, board);
    return <><div className="panel-label">СВОЙСТВА КОМПОНЕНТА</div><label className="field">Название компонента<input disabled={busy} value={component.name} maxLength={80} onChange={e => onComponentChange(component.id, { name: e.target.value })} /></label><span className="badge purple">{component.moduleId} / v{component.moduleVersion}</span>{incompatible ? <p className="inspector-warning"><TriangleAlert size={15} />{incompatible}</p> : <>
      <p className="panel-note">{module.description}</p><div className="property-divider" />
      {Object.entries(module.parameters).map(([key, parameter]) => <label className="field" key={key}>{parameter.label}{parameter.type === 'select' ? <select disabled={busy} value={component.parameters[key]} onChange={e => onComponentChange(component.id, { parameters: { ...component.parameters, [key]: e.target.value } })}>{parameter.options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input type="number" disabled={busy} min={parameter.min} max={parameter.max} step={parameter.step} value={component.parameters[key]} onChange={e => onComponentChange(component.id, { parameters: { ...component.parameters, [key]: Number(e.target.value) } })} />}</label>)}
      {module.constraints.requiresSeriesResistor && <div className="calculated-current"><span>Расчёт при 3,3 В</span><strong>{component.parameters.resistorOhms > 0 ? Math.max(0, (3.3 - component.parameters.forwardVoltage) / component.parameters.resistorOhms * 1000).toFixed(1) : '—'} мА</strong><small>Резистор физически обязателен. Расчёт не подтверждает реальное подключение.</small></div>}
      <div className="panel-label connections-heading">ПОДКЛЮЧЕНИЯ</div>{module.terminals.map(terminal => {
        const connected = project.assembly.connections.find(wire => wire.componentId === component.id && wire.terminalId === terminal.id);
        const missing = connected && !board.pins.some(pin => pin.id === connected.boardPinId);
        return <div className="terminal-setting" key={terminal.id}><label className="field">{terminal.label}<select aria-label={`Подключение: ${terminal.label}`} disabled={busy} value={connected?.boardPinId || ''} onChange={e => e.target.value ? onConnect(component.id, terminal.id, e.target.value) : onDisconnect(component.id, terminal.id)}><option value="">Не подключён</option>{missing && <option value={connected.boardPinId}>Контакт отсутствует: {connected.boardPinId}</option>}{board.pins.map(pin => { const problem = connectionProblem(project, catalog, component.id, terminal.id, pin.id); return <option key={pin.id} value={pin.id} disabled={Boolean(problem)}>{pin.label} · {pin.id}{problem ? ' · недоступен' : ''}</option>; })}</select></label>{connected && <button className="icon-button" disabled={busy} aria-label={`Отключить: ${terminal.label}`} onClick={() => onDisconnect(component.id, terminal.id)}><Unplug size={15} /></button>}</div>;
      })}<div className="panel-label connections-heading">РАСПОЛОЖЕНИЕ КОНТАКТОВ</div>{module.terminals.map(terminal => <label className="field" key={'side:' + terminal.id}>{terminal.label}<select aria-label={'Сторона контакта: ' + terminal.label} disabled={busy} value={terminalSide(module, terminal, project.assembly.portSides?.[component.id])} onChange={event => onTerminalSide(component.id, terminal.id, event.target.value)}>{Object.entries(TERMINAL_SIDES).map(([side, label]) => <option key={side} value={side}>{label}</option>)}</select></label>)}<p className="panel-note">Сторона меняет только расположение точки на схеме. Назначение контакта, GPIO и соединения сохраняются. Физические контакты не являются входами/выходами логического графа.</p><p className="panel-note">Или нажмите контакт компонента на холсте, затем контакт платы. GND допускает несколько соединений.</p>
    </>}
    <button className="button remove-component" disabled={busy} onClick={() => onRemoveComponent(component.id)}><Trash2 size={15} />Удалить компонент</button></>;
  }
  if (wire) {
    const owner = project.components.find(component => component.id === wire.componentId), definition = owner && moduleFor(owner, catalog);
    const terminal = definition?.terminals.find(item => item.id === wire.terminalId), target = board.pins.find(item => item.id === wire.boardPinId);
    const problem = connectionProblem(project, catalog, wire.componentId, wire.terminalId, wire.boardPinId);
    return <><div className="panel-label">СВОЙСТВА СОЕДИНЕНИЯ</div><h3 className="inspector-title">{owner?.name}</h3><div className="wire-detail"><strong>{terminal?.label || wire.terminalId}</strong><ArrowRight size={17} /><strong>{target?.label || wire.boardPinId}</strong></div><p className="panel-note">{terminal?.kind === 'ground' ? 'Общая земля, физическое соединение.' : 'Цифровой GPIO, физическое соединение.'}</p>{problem && <p className="inspector-warning"><TriangleAlert size={15} />{problem}</p>}<button className="button remove-component" disabled={busy} onClick={() => onRemoveWire(wire.id)}><Unplug size={16} />Удалить соединение</button></>;
  }
  if (pin) {
    const problem = pinProblem(project, pin, board);
    return <><div className="panel-label">КОНТАКТ ПЛАТЫ</div><h2 className="inspector-pin">{pin.label}</h2><span className="badge">{pin.id} · позиция {pin.physicalNumber}</span><div className="pin-status">{problem ? <><TriangleAlert size={17} /><span>{problem}</span></> : <><CheckCircle2 size={17} /><span>{pin.kind === 'gpio' ? 'Доступен для цифрового интерфейса' : pin.kind === 'ground' ? 'Общая земля / GND' : 'Питание или управление, не GPIO'}</span></>}</div><div className="property-pair"><span>Тип</span><strong>{pin.kind}</strong></div>{pin.gpio !== null && <div className="property-pair"><span>GPIO</span><code>{pin.gpio}</code></div>}{pin.functions.length > 0 && <p className="panel-note">Функции: {pin.functions.join(', ')}</p>}<p className="panel-note">{board.orientation}</p><p className="panel-note">Нажмите совместимый контакт компонента, чтобы соединить его с выбранным контактом платы.</p><Sources board={board} /></>;
  }
  return <><div className="panel-label">СВОЙСТВА ПЛАТЫ</div><div className="inspector-board"><Cpu size={28} /><div><h3>{board.name}</h3><small>{board.manufacturer}</small></div></div><p className={`board-confirmation ${board.pinoutVerified ? 'documented' : ''}`}><Info size={15} />{board.pinoutVerified ? 'По документации v1.1 N8R8' : 'Ревизия не подтверждена'}</p><p className="panel-note">{board.verificationNote}</p><div className="property-divider" /><div className="property-pair"><span>Микроконтроллер</span><strong>{board.mcu}</strong></div><div className="property-pair"><span>Целевой ESP-IDF</span><code>{board.espIdfVersion}</code></div><p className="panel-note orientation-note">{board.orientation}</p>{Object.entries(board.options || {}).map(([key, option]) => <label className="field" key={key}>{option.label}<select disabled={busy} value={project.boardSettings[key] || option.default} onChange={e => onBoardSetting(key, e.target.value)}>{option.values.map(value => <option key={value.value} value={value.value}>{value.label}</option>)}</select></label>)}{board.options?.camera && <p className="panel-note">Контакты камеры заблокированы, пока её отключение не подтверждено. GPIO16 также учитывает возможную перемычку VSYNC.</p>}<Sources board={board} /><div className="inspector-legend"><span><i className="legend-gpio" />GPIO</span><span><i className="legend-ground" />GND</span><span><i className="legend-power" />Питание</span><span><i className="legend-reserved" />Занят / ограничен</span></div><p className="fine-print">SVG сохраняет порядок контактов, но не служит масштабным чертежом платы. Работа с устройством пока не проверена.</p></>;
}
