import { useEffect, useRef, useState } from 'react';
import { Terminal, Hammer, Radio, Square, FileCode2, CheckCircle2, TriangleAlert } from 'lucide-react';
// ANSI escape sequences from the compiler are display control codes.
// eslint-disable-next-line no-control-regex
const strip=value=>value.replace(/\x1b\[[0-9;]*[A-Za-z]/g,'');
export default function ProcessPanel({idf,onPreview,issues,onIssue}){
 const [selectedTab,setTab]=useState(null);
 const tab=selectedTab || (idf.job?.operation==='monitor'?'monitor':'build');
 const log=useRef(null), follow=useRef(true);
 useEffect(()=>{if(follow.current && log.current)log.current.scrollTop=log.current.scrollHeight;},[idf.events,tab]);
 const errors=issues.filter(issue=>issue.severity==='error');
 const events=idf.events.filter(event=>tab==='monitor'?event.operation==='monitor':event.operation!=='monitor');
 const labels={running:'Выполняется',connected:'Подключён',stopping:'Останавливаем…',success:'Готово',failed:'Ошибка',cancelled:'Остановлено'};
 return <section className="process-panel"><header><div><button className={tab==='build'?'selected':''} onClick={()=>setTab('build')}><Hammer size={14}/>Сборка и прошивка</button><button className={tab==='monitor'?'selected':''} onClick={()=>setTab('monitor')}><Radio size={14}/>Serial</button><button className={tab==='check'?'selected':''} onClick={()=>setTab('check')}>Проверка{errors.length?` · ${errors.length}`:''}</button></div><span className={`process-state ${idf.job?.status==='failed'?'failed':''}`}>{idf.job?labels[idf.job.status]:idf.environment?'ESP-IDF готова':'Среда не проверена'}</span>{idf.busy&&idf.job&&<button className="text-button" onClick={idf.cancel}><Square size={12}/>Остановить</button>}<button className="icon-button" onClick={onPreview} disabled={!idf.preview} aria-label="Посмотреть исходники прошивки"><FileCode2 size={15}/></button></header><div className="process-log" ref={log} onScroll={()=>{const element=log.current;follow.current=element.scrollHeight-element.scrollTop-element.clientHeight<35;}} role="log" aria-label={tab==='monitor'?'Последовательный монитор':'Журнал компилятора'}>{tab==='check'?<div><p className="generation-state">{idf.generationError || 'Исходники готовы к сборке. Проверка схемы не подтверждает физический монтаж.'}</p>{issues.map((issue,index)=><button className="validation-row" key={`${issue.code}-${index}`} onClick={()=>onIssue(issue)}><span className={`log-level ${issue.severity==='error'?'error-level':'warning'}`}>{issue.severity==='error'?'ERR':'WARN'}</span><span>{issue.message}</span></button>)}</div>:!events.length?<div className="process-empty"><Terminal size={18}/><p>{tab==='monitor'?'Выберите подключённый порт и откройте монитор.':'Нажмите «Собрать». Журнал настоящей ESP-IDF появится здесь.'}</p></div>:tab==='monitor'?<pre className="serial-output">{strip(events.map(event=>event.stream==='stdout'?event.text:`\n[${event.status}] ${event.text}\n`).join(''))}</pre>:events.map(event=><div key={event.sequence} className={`process-line ${event.status==='failed'?'failed':''}`}><span className="process-stream">{event.status==='success'?<CheckCircle2 size={11}/>:event.status==='failed'?<TriangleAlert size={11}/>:event.stream==='stderr'?'ERR':event.stream==='system'?'SYS':'OUT'}</span><pre>{strip(event.text)}</pre></div>)}</div>{idf.build&&<footer><span>{idf.fresh?'Прошивка соответствует текущей схеме':'Схема/среда изменена – нужна новая сборка'}</span><code title={idf.build.binary}>{idf.build.binary}</code></footer>}</section>;
}
