import { useState } from 'react';
import { Cpu, RefreshCw, Download, CheckCircle2, Trash2, Square, FolderSearch, AlertCircle } from 'lucide-react';
import Modal from '../components/Modal.jsx';
import { SDK_STATES } from './sdkRequirements.js';
const bytes=value=>value<1024*1024*1024?`${(value/1024/1024).toFixed(1)} МиБ`:`${(value/1024/1024/1024).toFixed(1)} ГиБ`;
export default function SdkManager({idf}) {
 const [root,setRoot]=useState(idf.environment?.root || ''),[python,setPython]=useState(idf.environment?.python || '');
 const [version,setVersion]=useState('5.4.4'),[modal,setModal]=useState(null),[allowPrerequisites,setAllowPrerequisites]=useState(false),[confirmed,setConfirmed]=useState(false),[plan,setPlan]=useState(null),[planning,setPlanning]=useState(false);
 const snapshot=idf.sdks,active=snapshot?.active?.esp32s3;
 const installing=idf.job?.operation==='sdk_install';
 const sdkJob=idf.job?.operation.startsWith('sdk_');
 const events=sdkJob?idf.events:[];
 const progress=events.filter(event=>event.downloaded!==null&&event.downloaded!==undefined).at(-1);
 const percent=progress?.total?Math.min(100,Math.round(progress.downloaded/progress.total*100)):null;
 const stage=events.filter(event=>event.stream==='system'&&event.status==='running').at(-1)?.text;
 const unavailable=!idf.desktop||idf.busy||!idf.ready;
 const existingRequired=snapshot?.installations.find(sdk=>sdk.version===idf.requirement?.version && sdk.state==='ready');
 async function verify(path,interpreter){const result=await idf.check(path,interpreter);if(result){setRoot(result.root);setPython(result.python);}}
 async function prepare(version){setModal({type:'install',version});setAllowPrerequisites(false);setConfirmed(false);setPlan(null);setPlanning(true);try{setPlan(await idf.installPlan(version));}catch(error){idf.setError(String(error));}finally{setPlanning(false);}}
 const close=()=>{if(!planning)setModal(null);};
 return <>
 <section className="settings-card sdk-manager"><div className="settings-icon"><Cpu size={23}/></div><div>
  <h2>Инструменты разработки <span className={`badge ${idf.environment?'green':''}`}>{idf.checking?'Проверяем…':idf.environment?'Окружение готово':'Нужен SDK'}</span></h2>
  <p>Платформа ESP32-S3 · {idf.requirement?.name} {idf.requirement?.version}. SDK, Python, Xtensa GCC, CMake и Ninja выбираются вместе.</p>
  {!idf.desktop&&<p className="inspector-warning">Управление SDK доступно в десктопном приложении.</p>}
  {!idf.compatible&&idf.environment&&<p className="inspector-warning">ESP-IDF {idf.environment.sdkVersion} выбрана, но текущему генератору нужна {idf.requirement?.version}. Выберите совместимый SDK перед сборкой.</p>}
  <div className="sdk-actions"><button className="button secondary" disabled={unavailable} onClick={()=>idf.check()}><FolderSearch size={15}/>Найти и проверить SDK</button><button className="button secondary" disabled={unavailable} onClick={idf.refreshCatalog}><RefreshCw size={15}/>Обновить каталог</button><button className="button primary" disabled={unavailable || idf.compatible} onClick={()=>existingRequired?idf.selectSdk(existingRequired.id):prepare(idf.requirement?.version || '5.4.4')}>{existingRequired?<CheckCircle2 size={15}/>:<Download size={15}/>} {idf.compatible?'Нужный SDK готов':existingRequired?'Выбрать нужный SDK':'Установить нужный SDK'}</button></div>
  <h3 className="sdk-subheading">Установленные и обнаруженные SDK</h3>
  {!snapshot?.installations.length?<p className="sdk-empty">SDK не обнаружены. Можно подключить существующую установку или установить инструменты через EIM.</p>:<div className="sdk-list">{snapshot.installations.map(sdk=><article className={`sdk-row ${active===sdk.id?'active':''}`} key={sdk.id}><header><strong>ESP-IDF {sdk.version}</strong><span className={`badge ${sdk.state==='ready'?'green':''}`}>{SDK_STATES[sdk.state] || sdk.state}</span>{active===sdk.id&&<span className="sdk-active-label">Выбрана для ESP32-S3</span>}</header><code>{sdk.root}</code><small>{sdk.managed?'Управляется CLEX Flow':'Внешняя установка · удаление недоступно'}</small>{sdk.diagnostic&&sdk.state!=='ready'&&<p className="sdk-diagnostic">{sdk.diagnostic}</p>}<div className="sdk-row-actions"><button className="text-button" disabled={unavailable||sdk.state==='missing'||sdk.state==='installing'} onClick={()=>idf.selectSdk(sdk.id)}><CheckCircle2 size={14}/>Проверить и выбрать</button>{sdk.managed&&sdk.state!=='ready'&&<button className="text-button" disabled={unavailable} onClick={()=>prepare(sdk.version)}><RefreshCw size={14}/>Повторить установку</button>}{sdk.managed&&<button className="text-button sdk-delete" disabled={unavailable} onClick={()=>{setConfirmed(false);setModal({type:'remove',sdk});}}><Trash2 size={14}/>Удалить</button>}</div></article>)}</div>}
  <h3 className="sdk-subheading">Каталог ESP-IDF</h3><div className="sdk-catalog"><select aria-label="Версия SDK для установки" value={version} disabled={unavailable} onChange={event=>setVersion(event.target.value)}>{(snapshot?.available || [{version:'5.4.4',supported:true}]).map(item=><option value={item.version} key={item.version}>{item.version}{item.supported?' · текущий генератор':' · другие версии SDK'}</option>)}</select><button className="button secondary" disabled={unavailable || snapshot?.installations.some(sdk=>sdk.version===version && sdk.state==='ready')} onClick={()=>prepare(version)}><Download size={14}/>Установить версию</button></div>{snapshot?.catalogError&&<p className="sdk-diagnostic">{snapshot.catalogError} Используется сохранённый каталог.</p>}<p className="fine-print">Несколько версий хранятся отдельно. Установка другой версии SDK не расширяет автоматически совместимость генератора. Arduino, ESP8266, STM32, RP2040 и RP2350 пока не поддерживаются этим установщиком.</p>
  <details className="sdk-external"><summary>Указать существующую ESP-IDF</summary><label className="field">Каталог ESP-IDF<input value={root} disabled={idf.busy} onChange={event=>setRoot(event.target.value)} placeholder="Корень установки с tools/idf.py"/></label><label className="field">Python окружения ESP-IDF<input value={python} disabled={idf.busy} onChange={event=>setPython(event.target.value)} placeholder="Необязательно: путь к существующему Python"/></label><div className="button-row"><button className="button primary" disabled={!idf.desktop||idf.busy} onClick={()=>verify(root||null,python||null)}><CheckCircle2 size={15}/>Проверить пути</button><button className="button secondary" disabled={!idf.desktop||idf.busy} onClick={()=>verify('','')}><RefreshCw size={15}/>Найти автоматически</button></div></details>
  <label className="field console-mode">Консоль прошивки<select value={idf.consoleMode} disabled={idf.busy} onChange={event=>idf.setConsole(event.target.value)}><option value="usb">USB Serial/JTAG</option><option value="uart">UART0 · USB-UART bridge</option></select></label>
  {idf.environment&&<div className="tool-status"><span><CheckCircle2 size={14}/>{idf.environment.version}</span><code>{idf.environment.compilerVersion}</code><code>{idf.environment.cmakeVersion}</code><code>Ninja {idf.environment.ninjaVersion}</code><small>Python: {idf.environment.python}</small></div>}
  {sdkJob&&<div className="sdk-operation" role="log" aria-label="Журнал SDK Manager"><header><strong>{idf.busy?(stage || 'Выполняем операцию…'):{success:'Операция завершена',failed:'Ошибка',cancelled:'Остановлено'}[idf.job.status]}</strong>{idf.busy&&idf.job.operation!=='sdk_remove'&&<button className="text-button" onClick={idf.cancel}><Square size={13}/>Остановить</button>}</header>{installing&&idf.busy&&<><progress max={100} {...(percent!==null?{value:percent}:{})}/><small>{percent!==null?`EIM: ${percent}% · ${bytes(progress.downloaded)} из ${bytes(progress.total)}`:'SDK и компиляторы: этапы и загрузки отображаются в выводе EIM'}</small></>}<pre>{events.filter(event=>event.status!=='progress').map(event=>event.text+(event.stream==='system'?'\n':'')).join('')}</pre></div>}
  {idf.error&&<p className="inspector-warning"><AlertCircle size={15}/>{idf.error}</p>}
  <p className="fine-print">Новые SDK: {snapshot?.managedPath || 'отдельный каталог данных CLEX Flow'}. Обнаруженные установки используются по их исходным путям. Изменение версии делает прежнюю сборку неактуальной.</p>
 </div></section>
 {modal?.type==='install'&&<Modal title={`Установить ESP-IDF ${modal.version}?`} onClose={close} busy={planning}><p className="modal-intro">Официальный EIM загрузит SDK, компиляторы и Python-окружение в отдельный каталог CLEX Flow.</p><div className="sdk-install-summary">{planning?<p>Получаем размеры инструментов из официального манифеста…</p>:plan?<><strong>Оценка загрузки: {bytes(plan.estimatedMin)}-{bytes(plan.estimatedMax)}</strong><small>Инструменты из манифеста: {bytes(plan.toolBytes)}. Размер исходников SDK, Python-пакетов и системных зависимостей может отличаться.</small></>:<p>Оценка загрузки недоступна. Проверьте сеть и повторите попытку.</p>}<small>Требуется минимум 8 ГиБ свободного места.</small></div><label className="flash-confirm"><input type="checkbox" checked={allowPrerequisites} onChange={event=>setAllowPrerequisites(event.target.checked)}/>Разрешить EIM установить отсутствующие системные зависимости. На macOS может потребоваться Homebrew; на Windows используются официальные механизмы EIM.</label><label className="flash-confirm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Разрешаю полную загрузку и установку SDK.</label><footer><button className="button secondary" disabled={planning} onClick={close}>Отмена</button><button className="button primary" disabled={planning||!plan||!confirmed||idf.busy} onClick={()=>{setModal(null);idf.installSdk(modal.version,allowPrerequisites);}}><Download size={15}/>Установить</button></footer></Modal>}
 {modal?.type==='remove'&&<Modal title={`Удалить ESP-IDF ${modal.sdk.version}?`} onClose={close}><p className="modal-intro">Будут удалены SDK и его инструменты из управляемого каталога CLEX Flow. Отменить удаление нельзя.</p><code className="sdk-remove-path">{modal.sdk.slot}</code><label className="flash-confirm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Разрешаю удалить эту управляемую установку.</label><footer><button className="button secondary" onClick={close}>Отмена</button><button className="button danger" disabled={!confirmed||idf.busy} onClick={()=>{setModal(null);idf.removeSdk(modal.sdk.id);}}>Удалить SDK</button></footer></Modal>}
 </>;
}
